version: '3'
services:
  etl-process:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
      - es
    volumes:
      - etl_storage:/opt/app/storage

  db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
  es:
    image: elasticsearch:8.6.2
    container_name: es
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  etl_storage:
  esdata:
