version: '3'
services:
  etl-process:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - etl_storage:/opt/app/storage

  db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  etl_storage: